import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new MaterialApp(
      title: 'Shoping App',
      home: ShopingList(
        products: <Product>[
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
          Product(name: 'Eggs'),
          Product(name: 'Apples'),
          Product(name: 'Chocolate'),
        ],
      ),
    );
  }
}

class ShopingList extends StatefulWidget {
  final List<Product> products;

  ShopingList({this.products});

  @override
  State<StatefulWidget> createState() => ShopingListState();
}

class ShopingListState extends State<ShopingList> {
  Set<Product> shopingCart = Set<Product>();

  void handleCartChanged(Product product, bool inCart) {
    setState(() {
      if (inCart) {
        shopingCart.remove(product);
      } else {
        shopingCart.add(product);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        title: new Text('Shoping List'),
      ),
      body: new ListView(
        padding: EdgeInsets.symmetric(vertical: 8.0),
        children: widget.products.map((Product product) {
          return ShopingListItem(
            product: product,
            inCart: shopingCart.contains(product),
            onCartChanged: handleCartChanged,
          );
        }).toList(),
      ),
    );
  }
}

class ShopingListItem extends StatelessWidget {
  final Product product;
  final onCartChanged;
  final bool inCart;

  ShopingListItem({this.inCart, this.onCartChanged, this.product});

  Color getColor(BuildContext context) {
    return inCart ? Colors.black54 : Theme.of(context).primaryColor;
  }

  TextStyle getTextStyle(BuildContext context) {
    if (inCart) {
      return TextStyle(
          color: Colors.black54, decoration: TextDecoration.lineThrough);
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new ListTile(
      onTap: () {
        print(inCart);
        onCartChanged(product, inCart);
      },
      leading: new CircleAvatar(
        backgroundColor: getColor(context),
        child: new Text(product.name[0]),
      ),
      title: new Text(product.name, style: getTextStyle(context)),
    );
  }
}

class Product {
  final String name;

  Product({this.name});
}
